credentials:
  usernames:
    admin:
      email: admin@windeurope.com
      name:  admin
      password: "wind2026"

cookie:
  expiry_days: 30
  key: windeurope_2026_secure_enterprise_platform_key_987654321
  name: windeurope_cookie

preauthorized:
  emails:
    - admin@windeurope.com