credentials:
  usernames:
    admin:
      email: admin@windeurope.com
      name: Pedro
      password: "$2b$12$1K8QmSx9L8bQw4QkQxY6Qe8G5L6l0n5s0l4v0h2r6n6fP8lAq"

cookie:
  expiry_days: 30
  key: some_signature_key
  name: windeurope_cookie

preauthorized:
  emails:
    - admin@windeurope.com