```yaml
credentials:
  usernames:

    admin:
      email: admin@windeurope.com
      name: Pedro
      password: "$2b$12$MWnCwYk1b7Jx0M2u7nS8UuM3fM5s8wXx4x2M8l9pQfQ7uT8bM"

cookie:
  expiry_days: 30
  key: windeurope_cookie_key
  name: windeurope_cookie

preauthorized:
  emails:
    - admin@windeurope.com
```
